<script lang="ts">
	import { resolve } from '$app/paths';
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();

	function formatDate(date: Date): string {
		return new Intl.DateTimeFormat('en', {
			dateStyle: 'medium'
		}).format(date);
	}
</script>

<svelte:head>
	<title>{data.post.title} | true_log</title>
	<meta name="description" content={data.post.description} />
</svelte:head>

<main class="mx-auto w-full max-w-3xl px-4 py-8 pb-16 text-gray-800">
	<a
		class="mb-8 inline-flex font-bold text-indigo-600 no-underline hover:underline"
		href={resolve('/blog')}
	>
		Back to blog
	</a>

	<header class="mb-10">
		<p class="mb-2 text-sm font-bold text-indigo-600 uppercase">Blog</p>
		<h1 class="mb-4 text-4xl leading-tight font-bold sm:text-5xl">{data.post.title}</h1>
		<p class="mb-5 text-lg leading-relaxed text-gray-600">{data.post.description}</p>

		<dl class="mb-5 grid gap-3 sm:grid-cols-2">
			<div class="grid gap-1">
				<dt class="text-[0.8125rem] font-bold text-gray-500 uppercase">Published</dt>
				<dd class="text-gray-700">
					<time datetime={data.post.publishedAt.toISOString()}>
						{formatDate(data.post.publishedAt)}
					</time>
				</dd>
			</div>
			<div class="grid gap-1">
				<dt class="text-[0.8125rem] font-bold text-gray-500 uppercase">Updated</dt>
				<dd class="text-gray-700">
					{#if data.post.updatedAt}
						<time datetime={data.post.updatedAt.toISOString()}>
							{formatDate(data.post.updatedAt)}
						</time>
					{:else}
						Not updated
					{/if}
				</dd>
			</div>
		</dl>

		<ul class="m-0 flex list-none flex-wrap gap-2 p-0" aria-label={`${data.post.title} tags`}>
			{#each data.post.tags as tag (tag)}
				<li class="rounded-full bg-indigo-50 px-2 py-1 text-[0.8125rem] text-indigo-800">{tag}</li>
			{/each}
		</ul>
	</header>

	<article
		class="leading-loose [&_a]:text-indigo-600 [&_code]:text-[0.95em] [&_h1]:mt-8 [&_h1]:mb-3 [&_h1]:leading-snug [&_h2]:mt-8 [&_h2]:mb-3 [&_h2]:leading-snug [&_h3]:mt-8 [&_h3]:mb-3 [&_h3]:leading-snug [&_ol]:mb-5 [&_p]:mb-5 [&_pre]:overflow-x-auto [&_pre]:rounded-lg [&_pre]:bg-gray-950 [&_pre]:p-4 [&_pre]:text-gray-50 [&_ul]:mb-5"
	>
		<!-- eslint-disable-next-line svelte/no-at-html-tags -- HTML is generated by the server-side Markdown content layer. -->
		{@html data.post.html}
	</article>
</main>
