<script lang="ts">
	import { site } from '$lib/config/site';
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();
</script>

<svelte:head>
	<title>{data.page.title} | {site.name}</title>
	<meta name="description" content={data.page.description} />
</svelte:head>

<main class="mx-auto w-full max-w-3xl px-4 py-12 text-gray-800">
	<section
		class="prose prose-gray max-w-none prose-a:text-indigo-600"
		aria-labelledby="about-title"
	>
		<p class="text-sm font-bold text-indigo-600 uppercase">About</p>
		<h1 id="about-title">{data.page.title}</h1>
		<!-- eslint-disable-next-line svelte/no-at-html-tags -- HTML is generated by the server-side Markdown content layer. -->
		{@html data.page.html}
	</section>
</main>
