<script lang="ts">
	import { resolve } from '$app/paths';
	import { site } from '$lib/config/site';
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();

	function formatDate(date: Date): string {
		return new Intl.DateTimeFormat('en', {
			dateStyle: 'medium'
		}).format(date);
	}
</script>

<svelte:head>
	<title>{data.post.title} | {site.name}</title>
	<meta name="description" content={data.post.description} />
</svelte:head>

<main
	class="mx-auto grid w-full max-w-6xl gap-10 px-4 py-8 pb-16 text-gray-800 lg:grid-cols-[minmax(0,1fr)_16rem]"
>
	<a
		class="inline-flex font-bold text-indigo-600 no-underline hover:underline lg:col-span-2"
		href={resolve('/posts')}
	>
		Back to posts
	</a>

	<div class="min-w-0">
		<header class="mb-10">
			<p class="mb-2 text-sm font-bold text-indigo-600 uppercase">Posts</p>
			<h1 class="mb-4 text-4xl leading-tight font-bold sm:text-5xl">{data.post.title}</h1>
			<p class="mb-5 text-lg leading-relaxed text-gray-600">{data.post.description}</p>

			<dl class="mb-5 grid gap-3 sm:grid-cols-3">
				<div class="grid gap-1">
					<dt class="text-[0.8125rem] font-bold text-gray-500 uppercase">Published</dt>
					<dd class="text-gray-700">
						<time datetime={data.post.publishedAt.toISOString()}>
							{formatDate(data.post.publishedAt)}
						</time>
					</dd>
				</div>
				<div class="grid gap-1">
					<dt class="text-[0.8125rem] font-bold text-gray-500 uppercase">Updated</dt>
					<dd class="text-gray-700">
						{#if data.post.updatedAt}
							<time datetime={data.post.updatedAt.toISOString()}>
								{formatDate(data.post.updatedAt)}
							</time>
						{:else}
							Not updated
						{/if}
					</dd>
				</div>
				<div class="grid gap-1">
					<dt class="text-[0.8125rem] font-bold text-gray-500 uppercase">Read</dt>
					<dd class="text-gray-700">{data.post.readingTime.text}</dd>
				</div>
			</dl>

			<ul class="m-0 flex list-none flex-wrap gap-2 p-0" aria-label={`${data.post.title} tags`}>
				{#each data.post.tags as tag (tag)}
					<li class="rounded-full bg-indigo-50 px-2 py-1 text-[0.8125rem] text-indigo-800">
						{tag}
					</li>
				{/each}
			</ul>
		</header>

		<article
			class="prose prose-gray max-w-none prose-a:text-indigo-600 prose-headings:scroll-mt-24 prose-pre:bg-gray-950 [&_.heading-anchor]:ml-2 [&_.heading-anchor]:text-indigo-500 [&_.heading-anchor]:no-underline [&_.heading-anchor]:opacity-70 hover:[&_.heading-anchor]:opacity-100"
		>
			<!-- eslint-disable-next-line svelte/no-at-html-tags -- HTML is generated by the server-side Markdown content layer. -->
			{@html data.post.html}
		</article>

		<nav
			class="mt-12 grid gap-4 border-t border-gray-200 pt-6 sm:grid-cols-2"
			aria-label="Post navigation"
		>
			{#if data.navigation.previous}
				<a
					class="rounded-lg border border-gray-200 bg-white p-4 text-gray-700 no-underline hover:border-indigo-200 hover:text-indigo-700"
					href={resolve('/posts/[slug]', { slug: data.navigation.previous.slug })}
				>
					<span class="mb-2 block text-xs font-bold text-gray-500 uppercase">Previous post</span>
					<span class="block font-bold">{data.navigation.previous.title}</span>
				</a>
			{:else}
				<div class="rounded-lg border border-gray-200 p-4 text-gray-400">
					<span class="mb-2 block text-xs font-bold uppercase">Previous post</span>
					<span class="block">No older post</span>
				</div>
			{/if}

			{#if data.navigation.next}
				<a
					class="rounded-lg border border-gray-200 bg-white p-4 text-right text-gray-700 no-underline hover:border-indigo-200 hover:text-indigo-700"
					href={resolve('/posts/[slug]', { slug: data.navigation.next.slug })}
				>
					<span class="mb-2 block text-xs font-bold text-gray-500 uppercase">Next post</span>
					<span class="block font-bold">{data.navigation.next.title}</span>
				</a>
			{:else}
				<div class="rounded-lg border border-gray-200 p-4 text-right text-gray-400">
					<span class="mb-2 block text-xs font-bold uppercase">Next post</span>
					<span class="block">No newer post</span>
				</div>
			{/if}
		</nav>
	</div>

	{#if data.post.toc.length > 0}
		<aside class="lg:sticky lg:top-6 lg:self-start" aria-labelledby="toc-title">
			<h2 id="toc-title" class="mb-3 text-sm font-bold text-gray-500 uppercase">On this page</h2>
			<nav class="border-l border-gray-200 pl-4" aria-label="Table of contents">
				<ol class="m-0 grid list-none gap-2 p-0 text-sm">
					{#each data.post.toc as item (item.id)}
						<li class={item.depth === 3 ? 'pl-4' : undefined}>
							<a class="text-gray-600 no-underline hover:text-indigo-600" href={`#${item.id}`}>
								{item.text}
							</a>
						</li>
					{/each}
				</ol>
			</nav>
		</aside>
	{/if}
</main>
